### ISSUE TITLE
Nextcloud desktop client exclusively on OSX breaks, cause is server SSL protocols / ciphers.

### ISSUE THREAD

**Issue by kroko** [nextcloud/client_theming#64]
## Issue

First of all this most probably has to do how you build/pack Nextcloud client app, as your dependency is OC client 2.2.4 (through submodule), and that does not show this issue.

**On OSX using Nextcloud client app 2.2.4 one cannot connect to HTTPS if server is using strong  (as it should! 😄 ) SSL protocols / ciphers.**

Meanwhile

- **On OSX OC desktop app 2.2.4 works with strong server ciphers**
- **On MSW both OC 2.2.4 and NC 2.2.4 desktop app works with strong server ciphers**

Thus seemingly this issue is only for Nextcloud client AND only on OSX.

Please could you check if it is your NC build thing (or some Qt upstream issue?).

For now I have downgraded server SSL and will bring them up once this is resolved.

*I could not find more appropriate repo for this issue in `nextcloud/*` pool*

## Duplicate

As of posting this, I did not search well enough, my bad. Apparently this is duplicate https://github.com/nextcloud/client_theming/issues/13

## Steps to the revelation

I just did switch from OC 9.1.3.1 to NC 11.0.1.2

The switching was done by
- Turning off opcache
- Putting OC in maintenance mode
- Backuping everything
- Changing all files from OC to NC
- Adding back `config.php` fron OC to NC
- Changing only one value in `config.php` (`log_type` key value from `owncloud` to `file`)
- Doing `php occ upgrade`
- Exiting NC from maintanence mode 
- Turning on opcache

Thus the upgrade did nothing to change anything in server settings whatsoever.

**The web interface all works nicely (changin theme colors, yeeey 😄 ).**

I checked computers running OSX 10.11, MSW 10, if the OC client 2.2.4 app is working.

**OC client app 2.2.4 is working with NC 11.0.1. on both MSW and OSX**

On one MSW 10 machine I deleted OC client app and installed NC by doing

- Unchecked to launch on startup
- Exited the OC client app
- Uninstalled via Add/Remove programs
- Did full restart so that everything is cleaned
- Installed NC client app
- Logged in to `https://ourcloudhost.tld/`
- Set directory same as previously
- Opted to keep files
- Sync happened super fast
- Pushed some files here and there, server sees them, all other computers running OC desktop app sees them
- All OK!

On one OSX 10.11 machine I deleted OC client app and installed NC by doing

- Unchecked to launch on startup
- Exited the OC client app
- Trashed it (*zapped* also preferences and cache files)
- Did full restart so that everything is cleaned
- Installed NC client app

But I could not connect to server as every time I enter the server URI `https://ourcloudhost.tld/` in "Connect o Nextcloud" dialog I get.

```
Timeout while trying to connect to Nextcloud at https://ourcloudhost.tld/status.php.
```

`https://ourcloudhost.tld/status.php` is reachable via browser and returns

```json
{
"installed": true,
"maintenance": false,
"needsDbUpgrade": false,
"version": "11.0.1.2",
"versionstring": "11.0.1",
"edition": "",
"productname": "WARP CLOUD"
}
```

In LAN the cloud is also reachable via HTTP (because of nginx proxy that is sitting in front of it and doing SSL termination for WAN). In the dialog, when I try to connect to `http://ourcloudhost.tld/` I immediately get to the next step where username and password is asked.

So then first for a test I tried fixing NC by thinking that there is something about DB, because `config.php` had `'overwrite.cli.url' => 'http://ourcloudhost.tld',` (changed to `https`). Put it into maintenance mode, did repair, brought it back from maintenance mode (note the failed stuff, but this is probably related to https://github.com/nextcloud/server/issues/2566 ?)

```sh
$ php occ maintenance:repair
Nextcloud is in maintenance mode - no apps have been loaded
Failed to load repair step for dav: Repair step 'OCA\DAV\Migration\FixBirthdayCalendarComponent' is unknown
Failed to load repair step for dav: Repair step 'OCA\DAV\Migration\ValueFixInsert' is unknown
 - Repair MySQL collation
 - Repair mime types
 - Repair legacy storages
 - Remove asset cache
     - Asset cache cleared.
 - Generate ETags for file where no ETag is present.
     - ETags have been fixed for 0 files/folders.
 - Clean tags and favorites
     - 0 tags of deleted users have been removed.
     - 0 tags for delete files have been removed.
     - 0 tag entries for deleted tags have been removed.
     - 0 tags with no entries have been removed.
 - Drop old database tables
 31/31 [============================] 100%
 - Drop old background jobs
 - Remove getetag entries in properties table
     - Removed 0 unneeded "{DAV:}getetag" entries from properties table.
 - Repair outdated OCS IDs
 - Repair invalid shares
 - Remove old share propagation app entries
 - Remove old (< 9.0) calendar/contact shares
 4/4 [============================] 100%
 - Fix permissions so avatars can be stored again
 2/2 [============================] 100%
 - Remove shares of a users root folder
 - Repair unmerged shares
 - Move .step file of updater to backup location
 - Add move avatar background job
     - Repair step already executed
 - Add preview cleanup background jobs
 - Fix potential broken mount points
     - No mounts updated
```

Nothing changed.

Next possible stuff is SSL ciphers and HSTS. I turned to them because I have fought SSL battles on OS X before (not long time ago there was ~1 month in the past, where Safari (which uses OS HSTS, not browser one (such as Chrome, FF))  did not load our developed and deployed web apps, we had to change PROD server settings, because of OpenSSL mixup in OS), maddening frustrating.  
I allowed all protocols and low strength ciphers (you can see the corresponding commented out lines)

```
###############################
# SSL

SSLEngine on

#SSLVerifyClient none
#SSLVerifyDepth 1

#SSLProtocol All -SSLv2 -SSLv3 -TLSV1
SSLProtocol All

SSLHonorCipherOrder On
#SSLCipherSuite ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+3DES:DH+3DES:RSA+AESGCM:RSA+AES:RSA+3DES:!aNULL:!eNULL:!LOW:!MD5:!EXP:!PSK:!SRP:!DSS:!SSLv3:!SSLv2:!TLSv1
SSLCipherSuite ALL:!aNULL:RC4+RSA:+HIGH:+MEDIUM:+LOW:+EXP:+eNULL

SSLCertificateFile /path/to/cert.crt
SSLCertificateKeyFile /path/to/cert.key
SSLCertificateChainFile /path/to/cert-intermediate.crt

<FilesMatch "\.(cgi|shtml|phtml|php)$">
    SSLOptions +StdEnvVars
</FilesMatch>
<Directory /usr/lib/cgi-bin>
    SSLOptions +StdEnvVars
</Directory>

BrowserMatch "MSIE [2-6]" \
    nokeepalive ssl-unclean-shutdown \
    downgrade-1.0 force-response-1.0
BrowserMatch "MSIE [7-9]" ssl-unclean-shutdown

###############################
# Enable HTTP Strict Transport Security
<IfModule mod_headers.c>
  Header always set Strict-Transport-Security "max-age=15768000; includeSubDomains; preload"
</IfModule>
```

And of course I cleared HSTS cache on OSX as it is user-space-wide.

```
rm ~/Library/Cookies/HSTS.plist
sudo reboot
```

After reboot logging to server using Nextcloud 2.2.4 and  `https://ourcloudhost.tld/` works. 

- Set directory same as previously
- Opted to keep files
- Sync happened super fast
- Pushed some files here and there, server sees them, all other computers running OC desktop app sees them, MSW computer running NC desktop app sees them.
- All OK!

Regards,
kroko

**Comment by tflidd** [comment]
Duplicate? https://github.com/nextcloud/client_theming/issues/13

**Comment by thomaskonrad** [comment]
I have the same issue. I [posted this in the ownCloud client repository](https://github.com/owncloud/client/issues/5465) because i saw that the Nextcloud client uses the ownCloud client as a submodule and only changes the theme. However, it seems that the SSL/TLS client behaves differently in both clients.

Here are my details:

nginx configuration:

```
ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
ssl_ciphers 'EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH';
ssl_prefer_server_ciphers on;
ssl_dhparam /etc/ssl/dhparams.pem;
ssl_session_cache shared:SSL:10m;
ssl_stapling on;
ssl_stapling_verify on;
```

Confirmed by the Qualys SSL server test:

```
Protocols
TLS 1.2	Yes
TLS 1.1	Yes
TLS 1.0	Yes
SSL 3	No
SSL 2	No
```

Complete list of supported ciphers by my server:

```
# TLS 1.2 (suites in server-preferred order)
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (0xc030)   ECDH secp256r1 (eq. 3072 bits RSA)   FS	256
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (0xc02f)   ECDH secp256r1 (eq. 3072 bits RSA)   FS	128
TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 (0x9f)   DH 2048 bits   FS	256
TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 (0x9e)   DH 2048 bits   FS	128
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 (0xc028)   ECDH secp256r1 (eq. 3072 bits RSA)   FS	256
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA (0xc014)   ECDH secp256r1 (eq. 3072 bits RSA)   FS	256
TLS_DHE_RSA_WITH_AES_256_CBC_SHA256 (0x6b)   DH 2048 bits   FS	256
TLS_DHE_RSA_WITH_AES_256_CBC_SHA (0x39)   DH 2048 bits   FS	256

# TLS 1.1 (suites in server-preferred order)
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA (0xc014)   ECDH secp256r1 (eq. 3072 bits RSA)   FS	256
TLS_DHE_RSA_WITH_AES_256_CBC_SHA (0x39)   DH 2048 bits   FS	256

# TLS 1.0 (suites in server-preferred order)
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA (0xc014)   ECDH secp256r1 (eq. 3072 bits RSA)   FS	256
TLS_DHE_RSA_WITH_AES_256_CBC_SHA (0x39)   DH 2048 bits   FS	256
```

Resulting connection details (which is bullshit because SSLv3 is disabled for sure):

![screen shot 2017-01-21 at 18 20 30](https://cloud.githubusercontent.com/assets/2149539/22176354/ac9bdd5e-e008-11e6-8395-8e6a70528a6e.png)

**Comment by tflidd** [comment]
The client team on owncloud is currently working on a new release where they include a newer version of Qt (https://github.com/owncloud/client/issues/3449). You can install a daily version and test if this works with OS X (https://download.owncloud.com/desktop/daily/). Next step would be, to try and build a version with the Nextcloud theming and test that.

There probably won't be a next version in the 2.2.x-branch, so we should make sure that at least the new 2.3.x-build of Nextcloud works properly.

**Comment by kroko** [comment]
Pardon for duplicate. Edited my question referencing it.

**Comment by loongyh** [comment]
Just downloaded and tested [2.3.0.4rc1](https://download.nextcloud.com/desktop/prereleases/Mac/Nextcloud-2.3.0.4rc1.pkg) released several hours ago, issue is fixed. Thanks and awesome work Nextcloud team!

**Comment by enoch85** [comment]
> Just downloaded and tested 2.3.0.4rc1 released several hours ago, issue is fixed. Thanks and awesome work Nextcloud team!

**Comment by kroko** [comment]
Why was this closed? https://nextcloud.com/install/#install-clients still supplies Nextcloud-2.2.4.1, where the issue persists.

**Comment by enoch85** [comment]
@rullzer Can you please release the latest version for Mac and close this issue? Thanks!

**Comment by roedie** [comment]
This is silly, I'm still using the owncloud app because of this issue.

**Comment by jmfederico** [comment]
I agree with @roedie.

**Comment by rullzer** [comment]
get 2.3.2 at https://nextcloud.com/install/#install-clients

**Comment by helmut72** [comment]
Closed? Still won't work with v2.3.2.1. Also need to use OC client on my Mac.

**Comment by derkostka** [comment]
@rullzer unfortunately, the release does not solve the problem for me either. OC Client works, can you please create a new release so i can cross-check ? Thanks !

**Comment by JaredBoone** [comment]
@rullzer FYI, this is not fixed in 2.3.2. Please see the comments in #13. It seems that the Qt library used to build the client was not built using the correct OpenSSL configuration. I have successfully built a "secure" version of the 2.3.2 client by using the following configuration step when building Qt 5.6.2: 
`OPENSSL_LIBS="/usr/local/opt/openssl/lib/libcrypto.a /usr/local/opt/openssl/lib/libssl.a -lcrypto -lssl" ./configure -sdk macosx10.9 -openssl -openssl-linked -I/usr/local/opt/openssl/include -opensource -nomake examples -nomake tests`

**Comment by kroko** [comment]
I opened this ticket on January 20th, still not solved. The issue has not gained that much of a traction amongst NC users which - although this affects only OSX clients - makes me wonder how many run their NC installations either with archaic cipher settings or no security at all. Fine, one could say it's their fault, because (just checked) newest NC docs at last mention the need to configure SSL ciphers. But the fact that it has not gained much traction amongst devs is worrying - whether there are no resources to work on security or security is low priority, both are bad signals.  
<sub>Whenever writing tickets for open source projs I feel the need to say proper thanks and to apologise for not fixing it myself, thus - thank you and pardon. But please, fix it!</sub>

**Comment by roedie** [comment]
@kroko I think the problem here is that there is an alternative that works. I use the owncloud desktop client because the nextcloud devs don't seem to care about their client.

Even if this bug gets fixed I might not even switch since the time to fix is exceptionally long.

**Comment by kroko** [comment]
... agree @roedie. which is shooting themselves in the foot.  
Technically - What happens at the moment when OC client becomes incompatible with NC backend because of branching too far off. The faces of my colleagues and yet another ticket here... which could be avoided if things were in sync between NC client and NC server. I keep in mind that this day might come when all work will literally stop, because no file exchange will be possible - although on every NC update I double check forums if changes are not breaking in respect to Client<->Server, I might miss something.
NC market interests - whenever I brief my new colleagues "we use a tool to collaborate inhouse on all projects", they have to be pointed to owncloud site to download the client app. I have colegues that have come to me and said - I set up owncloud(!) at home for my family too!
money (small, but still) - company pays for all user smartphone apps for all collegues, currently money goes to OC client (I do not wish to research if NC iOS app has same issues as OSX app, I simply assume that NC clients are broken).
In the end it is not that hard to migrate from NC to other cloud platform. TBs I am currently managing would take a day, to push to other platform (say, back to OC) and recrawl databases. In the end "the client" (the needs of the enduser) will win, it does not matter if NC had better server code and smaller CPU footprint whatsoever. CPU power is cheap, time is not!
_big sad. huge sad. big problem._

**Comment by tflidd** [comment]
There is a pre-release that seems to work for a few people:
https://github.com/nextcloud/client_theming/issues/13#issuecomment-337147310

This is somehow a duplicate of https://github.com/nextcloud/client_theming/issues/13?


> big sad. huge sad. big problem.

Not a nice situation indeed. The working owncloud client (only an issue on mac desktop client, other desktops and all mobile devices work) didn't make it a top priority. However, things move forward and Nextcloud wants to implement end-to-end-encryption on the client which means they move on to develop their own desktop client:
https://help.nextcloud.com/t/nextcloud-introducing-native-integrated-end-to-end-encryption/21579
